### ISSUE TITLE
Method InterceptAsync of AsyncInterceptorBase invokes many times

### ISSUE THREAD

**Issue by denis-tsv** [JSkimming/Castle.Core.AsyncInterceptor#107]
I created an interceptor

    public class RunSettingsAsyncInterceptor : AsyncInterceptorBase
    {
        private readonly IRunSettingsService runSettingsService;
        public RunSettingsAsyncInterceptor(IRunSettingsService runSettingsService)
        {
            this.runSettingsService = runSettingsService;
        }

        protected override async Task InterceptAsync(IInvocation invocation, Func<IInvocation, Task> proceed)
        {
            await CheckSettingEnabled(invocation);

            await proceed(invocation);
        }

        protected override async Task<TResult> InterceptAsync<TResult>(IInvocation invocation, Func<IInvocation, Task<TResult>> proceed)
        {
            await CheckSettingEnabled(invocation);

            return await proceed(invocation);
        }

        private async Task CheckSettingEnabled(IInvocation invocation)
        {
            //request to database
        }
    }

Interceptor and service registered to ASP.NET DI Container

    services.AddTransient<RunSettingsAsyncInterceptor>();
    services.AddScoped<IRunSettingsService, RunSettingsService>();

How do I register a service in DI Container

    services.AddScoped<VoWRunService>();
    services.AddScoped<IVoWRunService>(sp => CreateProxyWithInterceptor<IVoWRunService, VoWRunService, RunSettingsAsyncInterceptor>(sp));          

Extension method to create a proxy

    private static TInterface CreateProxyWithInterceptor<TInterface, TImplementation, TInterceptor>(IServiceProvider serviceProvider)
            where TImplementation : TInterface
            where TInterface : class
            where TInterceptor : IAsyncInterceptor 
        {
            var service = serviceProvider.GetRequiredService<TImplementation>();
            var generator = new ProxyGenerator();
            var interceptor = serviceProvider.GetRequiredService<TInterceptor>();
            var proxy = generator.CreateInterfaceProxyWithTargetInterface<TInterface>(service, interceptor);
            return proxy;
        }

Method InterceptAsync<TResult> invokes many times, from 50 to 400. Every time I receive a new count of invocations.
Could you please advice how to resolve this issue? I use .NET Core 2.1 and ASP.NET Core

**Comment by JSkimming** [comment]
Are you using [1.7.0](https://www.nuget.org/packages/Castle.Core.AsyncInterceptor/1.7.0) or the latest [2.0.21-alpha](https://www.nuget.org/packages/Castle.Core.AsyncInterceptor/2.0.21-alpha)? I can see you're performing an asynchronous operation before calling proceed, and I suspect you're not on the latest as that was one of the major issues. The fix resulted in a breaking change, which is why there's going to be a major bump.

I've been making some changes to the build and release process recently, I'm hoping to release 2.0 soon. That latest alpha is pretty close to how it will be when released.

**Comment by denis-tsv** [comment]
I used 1.7.0, after update up to 2.0.21-alpha problem was solved. @JSkimming thank you for the answer!
