### ISSUE TITLE
New release to support awaits before proceed?

### ISSUE THREAD

**Issue by twsouthwick** [JSkimming/Castle.Core.AsyncInterceptor#108]
I'm seeing an error where if I call await before proceed, it fails. This appears to be known and fixed by https://github.com/JSkimming/Castle.Core.AsyncInterceptor/pull/27. However, there has been no release since this was put in. Is this going to be released any time soon?

**Comment by JSkimming** [comment]
@twsouthwick it's been released. If you install [2.0.21-alpha](https://www.nuget.org/packages/Castle.Core.AsyncInterceptor/2.0.21-alpha), you can call await before proceed.

I've been tidying up some of the CI changes (#101 & #103) as well as releasing the changes with support for nullable reference types (#83), I'm looking to move to pushing to NuGet via GitHub actions. I don't think will change much (if at all) when releasing a non-alpha 2.0 version, so go with the latest.
