### ISSUE TITLE
Register IAsyncInterceptor As Interceptor in Windsor Container

### ISSUE THREAD

**Issue by senvardarsemih** [JSkimming/Castle.Core.AsyncInterceptor#125]
I created LoggingInterceptor which implements **_IAsyncInterceptor_**. Normally I can register my LoggingInterceptor when it implements **_IInterceptor_**.
`
            windsorContainer
                .Register(Component.For<LoggingInterceptor>().LifestyleSingleton())
                .Register(Classes.FromAssembly(typeof(IApplyService).Assembly)
                .Where(c => c.Namespace != null &&
                            typeof(IService).IsAssignableFrom(c))
                .WithServiceAllInterfaces()
                .Configure(x => x.Interceptors<LoggingInterceptor>())
                .Configure(x => x.Named(x.Implementation.FullName))
                .LifestyleTransient());`

But when I implement **_IAsyncInterceptor_** , it says LoggingInterceptor  must be convertible Castle.DinamicProxy.IInterceptor.

How can i overcome this situation ? I am not using AutoFac as DI .

**Comment by JSkimming** [comment]
There are extension methods for `IAsyncInterceptor` and `IEnumerable<IAsyncInterceptor>` called [ToInterceptor()](https://github.com/JSkimming/Castle.Core.AsyncInterceptor/blob/v2.0.0/src/Castle.Core.AsyncInterceptor/ProxyGeneratorExtensions.cs#L21) and [ToInterceptors()](https://github.com/JSkimming/Castle.Core.AsyncInterceptor/blob/v2.0.0/src/Castle.Core.AsyncInterceptor/ProxyGeneratorExtensions.cs#L31) respectivly.

If I understand your code correctly, you want the following:

```csharp
windsorContainer
    .Register(Component.For<LoggingInterceptor>().LifestyleSingleton())
    .Register(Classes.FromAssembly(typeof(IApplyService).Assembly)
        .Where(c => c.Namespace != null && typeof(IService).IsAssignableFrom(c))
        .WithServiceAllInterfaces()
        .Configure(x => x.Interceptors<LoggingInterceptor>().ToInterceptors())
        .Configure(x => x.Named(x.Implementation.FullName))
        .LifestyleTransient());
```

**Comment by JSkimming** [comment]
Upon rereading, I think my snippet was wrong, and the compile error is with `x.Interceptors<LoggingInterceptor>()` and `LoggingInterceptor` not matching the generic constraints.

I'm not familiar with Castle Windsor but some use of [ToInterceptor()](https://github.com/JSkimming/Castle.Core.AsyncInterceptor/blob/v2.0.0/src/Castle.Core.AsyncInterceptor/ProxyGeneratorExtensions.cs#L21) and [ToInterceptors()](https://github.com/JSkimming/Castle.Core.AsyncInterceptor/blob/v2.0.0/src/Castle.Core.AsyncInterceptor/ProxyGeneratorExtensions.cs#L31) is the way to go.

**Comment by senvardarsemih** [comment]
Yes, the code block you suggested generates an error as you specified. I will try to work a little more for a solution with the extensions you mentioned. Thanks for the solution suggestion
