### ISSUE TITLE
Shortcut invocation

### ISSUE THREAD

**Issue by smolesen** [JSkimming/Castle.Core.AsyncInterceptor#14]
Hi

How would I shortcut the invocation of my async method. Lets say I want to return fast if some creteria is fullfilled, how would I do that?

/Søren

**Comment by JSkimming** [comment]
Hi Søren

I'm not sure what you mean by shortcut, do you mean not call the innovation at all, or call it and if it does not return within a certain period, return the default?

Either way think you need to implement `IAsyncInterceptor`, as [described here](https://github.com/JSkimming/Castle.Core.AsyncInterceptor/tree/v1.2.3#option-1--implement-iasyncinterceptor-interface-to-intercept-invocations).

Extending the `InterceptAsynchronous<TResult>` [example](https://github.com/JSkimming/Castle.Core.AsyncInterceptor/tree/v1.2.3#interceptasynchronoustresultiinvocation-invocation).

```csharp
public void InterceptAsynchronous<TResult>(IInvocation invocation)
{
    invocation.ReturnValue = InternalInterceptAsynchronous<TResult>(invocation);
}

private async Task<TResult> InternalInterceptAsynchronous<TResult>(IInvocation invocation)
{
    // Check whether to call invocation at all, and if not return the default.
    if (false)
        return default(TResult);

    // Execute the invocation and get the task to await.
    invocation.Proceed();
    Task<TResult> task = (Task<TResult>)invocation.ReturnValue;

    // Wait for the task but only wait 500 milliseconds.
    await Task.WhenAny(task, Task.Delay(500));

    // If the task completed successfully, return the result.
    if (task.IsCompleted && !task.IsCanceled && !task.IsFaulted)
        return task.Result;

    // Return the default of the task did not complete successfully.
    return default(TResult);
}
```

Does that help?

**Comment by smolesen** [comment]
Hi

I was just wondering if I could use it for (shorttime) caching. If I could return fast, if the result were already in the cache.

**Comment by JSkimming** [comment]
How and when you choose to cache is implementation dependent, and when I need to do this I don't tend to use a generic interception mechanism like DynamicProxy.

In this situation I use interfaces, and I have two implementations of the interface, something like this:

```csharp
public interface ISlowRequests
{
    Task<string> GetDataAsync(Guid id);
}

public class SlowDataSource : ISlowRequests
{
    public async Task<string> GetDataAsync(Guid id)
    {
        // get the information by the key from the slow data source.
    }
}

public class SlowRequestsCache : ISlowRequests
{
    private readonly ISlowRequests _inner;

    private static readonly ConcurrentDictionary<Guid, (DateTime expiry, string data)> _cache =
        new ConcurrentDictionary<Guid, (DateTime, string)>();

    public SlowRequestsCache(ISlowRequests inner)
    {
        _inner = inner;
    }

    public async Task<string> GetDataAsync(Guid id)
    {
        // Check if the data is in the cache.
        if (_cache.TryGetValue(id, out (DateTime expiry, string data) value))
        {
            // return the cached data if it has not expired.
            if (value.expiry > DateTime.UtcNow)
                return value.data;
        }

        // No cache hits, so get the data from the underlying source.
        string data = await _inner.GetDataAsync(id);

        // Cache the data for 30 minutes.
        _cache[id] = (DateTime.UtcNow.AddMinutes(30), data);

        return data;
    }
}
```

If course, this is a very simple example to illustrate the point, for more sophisticated caching you could use [Polly](https://github.com/App-vNext/Polly#cache). But the two implementations of the same interface is a good way to keep the concerns separate e.g. one implementation for data access, the other for caching.
