### ISSUE TITLE
Async Interceptor not working for more than one Interceptor

### ISSUE THREAD

**Issue by vinoddamupatil** [JSkimming/Castle.Core.AsyncInterceptor#17]
Hi,

Async Interceptor not gets hits for second Interceptor Its only picking first Interceptor,

I passed different named instances of Interceptor  and proxy generator but its not working for second interceptor. Second Interceptor not gets hit.

            container.Register(
                Component.For<IAsyncInterceptor>().ImplementedBy<MetricInterceptorAsync>()
                .Named("IRouterEventProcessorInterceptor")
                .DependsOn(Dependency.OnValue("metricName", MetricConstants.RouterEventProcessor))                 
                .LifestyleTransient());
            
            var eventProcessorInterceptor = container.Resolve<IAsyncInterceptor>("IRouterEventProcessorInterceptor");

            container.Register(Component.For<ProxyGenerator>()
                .Named("EventProcessorGenerator")
                .LifestyleTransient());
                
           var eventProcessorGenerator = container.Resolve<ProxyGenerator>("EventProcessorGenerator");

            var eventProcessor = container.Resolve<INotificationRouterEventProcessor>();

            var eventProcessorGeneratorProxy = eventProcessorGenerator.CreateInterfaceProxyWithTargetInterface<INotificationRouterEventProcessor>(eventProcessor, eventProcessorInterceptor);
            container.Register(Component.For<INotificationRouterEventProcessor>()
                .Instance(eventProcessorGeneratorProxy)
                .OverridesExistingRegistration()
                .LifestyleTransient());
                   
            container.Register(
                Component.For<IAsyncInterceptor>()
                    .ImplementedBy<MetricInterceptorAsync>()
                    .Named("IProfileServiceInterceptor")
                    .DependsOn(Dependency.OnValue("metricName", MetricConstants.ProfileApiService))
                    .LifestyleTransient());

             var profileApiInterceptor = container.Resolve<IAsyncInterceptor>("IProfileServiceInterceptor");

            var profileApiService = container.Resolve<IProfileApiService>();

            container.Register(Component.For<ProxyGenerator>()
                .Named("ProfileApiServiceGenerator")
                .LifestyleTransient());

            var profileApiServiceGenerator = container.Resolve<ProxyGenerator>("ProfileApiServiceGenerator");

            var profileApiServiceProxy = profileApiServiceGenerator.CreateInterfaceProxyWithTargetInterface<IProfileApiService>(profileApiService, profileApiInterceptor);            

            container.Register(Component.For<IProfileApiService>()
                .Instance(profileApiServiceProxy)
                .OverridesExistingRegistration()
                .LifestyleTransient());

Here profileApiServiceProxy, Interceptor not gets hit.

Thanks,
Vinod Patil

**Comment by JSkimming** [comment]
Hi @vinoddamupatil 

I've used AsyncInterceptor with the built in ASP.NET Core container, and it's working fine.

I don't think this has anything do with AsyncInterceptor but with your IoC container, or more to the point, your use of the IoC container.

I don't know why you are registering IAsyncInterceptor?

Can you isolate a problem to code that doesn't use an IoC container?

Jim
