### ISSUE TITLE
LICENSE file does not contain copyright info

### ISSUE THREAD

**Issue by kygagner** [JSkimming/Castle.Core.AsyncInterceptor#188]
I intend to use Castle.Core.AsyncInterceptor as part of a commercial product and it would help if I could properly attribute the software. Typically the LICENSE file is not the full text of the Apache license, but rather a boilerplate copyright and license notice referring to the Apache license. See bottom of page: https://www.apache.org/licenses/LICENSE-2.0#apply

**Comment by kygagner** [comment]
Apologies - the copyright boilerplate goes in a NOTICE file and you may leave the LICENSE file as-is

**Comment by JSkimming** [comment]
No problem. I'm always delighted to hear about this project's use and would want to avoid any mistake in the licence to prevent adoption. Thanks for checking.
