### ISSUE TITLE
Castle.Core AsyncInterceptor StrongName

### ISSUE THREAD

**Issue by cpgue** [JSkimming/Castle.Core.AsyncInterceptor#23]
Hello,

Can you please provide a strong signed package for AsyncInterceptor?

Thank you.

**Comment by JSkimming** [comment]
@cpgue I've not signed the assemblies of a package I've created before, do you know what it involves in regard to an automated CI environment in AppVeyor and Travis?

**Comment by cpgue** [comment]
@JSkimming 
There is a package called StrongNamer in the nuget gallery which will automatically sign your assembly. Not sure if it fits to your understanding of your developement design.

There are a few links which explain how to create a private/public key and sign your assembly.
https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-create-a-public-private-key-pair
https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name
