### ISSUE TITLE
Consider also accept `IProxyGenerator` in `ProxyGeneratorExtensions.cs`?

### ISSUE THREAD

**Issue by yyjdelete** [JSkimming/Castle.Core.AsyncInterceptor#29]

**Comment by JSkimming** [comment]
@yyjdelete I wasn't aware of the interface, is it a 1-4-1 replacement for `IProxyGenerator` insofar as could it just be implemented with a search and replace?

**Comment by yyjdelete** [comment]
I think it is.
The interface was introduced in 4.0.0-beta002
https://github.com/castleproject/Core/releases/tag/v4.0.0-beta002

**Comment by JSkimming** [comment]
Hi @yyjdelete, I'll have a look this weekend, and see if it's an easy change, though I'm happy to accept a pull request 😄 

If it is changed then it will be a breaking change (it changes a public API), therefore I'll update the major version number. That being the case I'll wait until I've had a chance to also include PR #28, to roll out both at once.
