### ISSUE TITLE
How to write unit test for classes implementing AsyncInterceptor

### ISSUE THREAD

**Issue by Dharam625** [JSkimming/Castle.Core.AsyncInterceptor#36]
Hi,

I have implemented asyncInterceptor to intercept methods. How do i start testing. I am using Nunit with c# for unit testing. Any example would be really appreciated.

Thanks in advance.

**Comment by JSkimming** [comment]
@Dharam625 It all depends on what you are trying to test.

For instance, I use interception for crosscutting concerns like logging and error handling. Therefore it's not appropriate to test the interceptors in a specific scenario.

If you want to test your interceptors, then you should be able to prove them in isolation as they implement interfaces or abstract base classes.

If you want to test whether the interceptors incept correctly, then something like the unit tests in this project would be a good example.
