### ISSUE TITLE
Question - Register IAsyncInterceptor with CastleWindsor as an Interceptor help wanted

### ISSUE THREAD

**Issue by SirLancelotDuLac** [JSkimming/Castle.Core.AsyncInterceptor#43]
I there

I´ve been trying to use your extension to register async interceptors with no success.</br>
I´ve been totalylost on how i can "tell" CastleWindsor to use a component that implements IAsyncInterceptor  as a interceptor.</br>
How can I specify that a component that implements ISumService(for example) should be resolved through CreateInterfaceProxyWithTargetInterface ? </br>

I know that this is a little off-topic, but i can´t find an answer for this.</br>

Thanks in advance.

**Comment by JSkimming** [comment]
@SirLancelotDuLac I'm afraid I don't know CastleWindsor well enough to help you, but I suspect you can roll your own, it's what I do with other DI frameworks, where I register factories that create the proxies.

**Comment by SirLancelotDuLac** [comment]
Thanks  
I´ll try to go on that direction. This topic has left me completly lost, because your idea is very helpfull and it solves me a problem.

Thanks
