### ISSUE TITLE
Add support for ProxyGenerator.CreateInterfaceProxyWithoutTarget

### ISSUE THREAD

**Issue by FrankyBoy** [JSkimming/Castle.Core.AsyncInterceptor#44]
Hi!

Would be neat if ProxyGeneratorExtensions also contained overloads for CreateInterfaceProxyWithoutTarget as that's our use case. 

Thanks 👍

**Comment by FrankyBoy** [comment]
PS: Looking at the code, I just found the extension method `ToInterceptor`, mentioning that one in the docs should also already be a huge help.

**Comment by JSkimming** [comment]
@FrankyBoy Feel free to submit a PR.

**Comment by JSkimming** [comment]
Thanks for the contribution @FrankyBoy very much appreciated 👍
