### ISSUE TITLE
More Admins

### ISSUE THREAD

**Issue by JSkimming** [JSkimming/Castle.Core.AsyncInterceptor#45]
Just putting this out there to see if people want to wade to maintain this library.

So far both @ndrwrbgs and @brunoblank have made significant contributions, I was wondering if you guys would like to become admins.

The CI automation it working well, but I still, out of choice, manually push to NuGet. Automated push to NuGet would make shared admin easier. I'm open to ideas on the best way. I know how to push to NuGet from the CI I'm just doing it manually to finely controll the versions and releases in GitHub.

**Comment by brunoblank** [comment]
Hi, yes I would like to help out.

Regards 
/Bruno

**Comment by JSkimming** [comment]
@ndrwrbgs, do you want to join in too?

It would be good to share the power. It would also be good to share build access and NuGet push power too.

WDYT?

**Comment by ndrwrbgs** [comment]
I’m willing to assist but would prefer to stay out of being _primary_ owner of anything :)

**Comment by JSkimming** [comment]
@ndrwrbgs, of course, I see myself as benevolent dictator 😉
