### ISSUE TITLE
Expected Release Date

### ISSUE THREAD

**Issue by FernandoNunes** [JSkimming/Castle.Core.AsyncInterceptor#53]
Hey guys,

I've been reading your efforts and Castle.Core's efforts for making a truly awaitable interceptor (before & after proceed) and want to congratulate you, good job.

However we do have a question, as we really need this changes to be publicly available.
When can we expect this branch to be merged to master and a new NuGet released ?

Best Regards,
Fernando Nunes

**Comment by JSkimming** [comment]
@FernandoNunes I'm having a look now, though we can't release anything to NuGet until the necessary changes from castleproject/Core#439 have been released to NuGet.

**Comment by stakx** [comment]
FYI Castle.Core 4.4.0 has been published on NuGet today.

**Comment by JSkimming** [comment]
I've just pushed [2.0.0-alpha](https://www.nuget.org/packages/Castle.Core.AsyncInterceptor/2.0.0-alpha) to NuGet.

**Comment by FernandoNunes** [comment]
We've downloaded the 2.0.0-alpha and are already using it, great job.

Best Regards,
Fernando Nunes
