### ISSUE TITLE
How to use with Castle.Core.InterceptorAttribute?

### ISSUE THREAD

**Issue by DianaKoenraadt** [JSkimming/Castle.Core.AsyncInterceptor#81]
This seems like exactly what I'm looking for. 
I've implemented IAsyncInterceptor and now I want to test. But, I'm using InterceptorAttribute on my IoC managed class:

    [Interceptor(typeof(MyAsynchronousInterceptor))]
    class MyClass
    {
    }

However, I'm getting the error `An interceptor registered for F1307.HmiClient.WCF.ClientConnectionManager doesn't implement the IInterceptor interface`

How can I use it with the attribute?

**Comment by JSkimming** [comment]
@DianaKoenraadt the [AsyncDeterminationInterceptor](https://github.com/JSkimming/Castle.Core.AsyncInterceptor/blob/v2.0.21-alpha/src/Castle.Core.AsyncInterceptor/AsyncDeterminationInterceptor.cs) class implements `IInterceptor`. There's an extension method [ToInterceptor](https://github.com/JSkimming/Castle.Core.AsyncInterceptor/blob/v2.0.21-alpha/src/Castle.Core.AsyncInterceptor/ProxyGeneratorExtensions.cs#L15-L23) to help with the conversion.

Can you get either of those two options to work?

**Comment by DianaKoenraadt** [comment]
I ended up writing my own wrapper that implements `IInterceptor` and that calls ToInterceptor. And then I bootstrap the wrapper and use it in `InterceptorAttribute`. If you could provide something like this in your library, that'd be a great addition :)

**Comment by JSkimming** [comment]
@DianaKoenraadt This library is IoC container agnostic. To implement something for a specific container is not something I'd like to add.

I would be happy to receive generic changes to support IoC containers; please do provide a PR for review. Also, a documentation update on what you have implemented would be similarly welcome, as it is likely others could benefit from your experience.

I'm going to close this issue now as it looks resolved.

**Comment by DianaKoenraadt** [comment]
Here's an example for anyone (me) searching for this years later.


    public class AsyncLoggingInterceptor : IInterceptor
    {
        private ILogger _logger;

        public AsyncLoggingInterceptor(ILogger logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public void Intercept(IInvocation invocation)
        {
            var interceptor = new LoggingAsyncInterceptor(_logger);
            var asyncInterceptor = interceptor.ToInterceptor();
            asyncInterceptor.Intercept(invocation);
        }
    }

    public class LoggingAsyncInterceptor : AsyncInterceptorBase
    {
        private ILogger _logger;

        public LoggingAsyncInterceptor(ILogger logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        protected override async Task InterceptAsync(IInvocation invocation, Func<IInvocation, Task> proceed)
        {
            _logger.Trace($"ENTERED METHOD: {invocation.Method.DeclaringType.FullName}.{invocation.Method.Name}");

            // Cannot simply return the the task, as any exceptions would not be caught below.
            await proceed(invocation).ConfigureAwait(false);

            _logger.Trace($"EXITED METHOD: {invocation.Method.DeclaringType.FullName}.{invocation.Method.Name}");
        }

        protected override async Task<T> InterceptAsync<T>(IInvocation invocation, Func<IInvocation, Task<T>> proceed)
        {
            _logger.Trace($"ENTERED METHOD: {invocation.Method.DeclaringType.FullName}.{invocation.Method.Name}");

            // Cannot simply return the the task, as any exceptions would not be caught below.
            var result = await proceed(invocation).ConfigureAwait(false);

            _logger.Trace($"EXITED METHOD: {invocation.Method.DeclaringType.FullName}.{invocation.Method.Name}");

            return result;
        }
    }


Usage:


    [Interceptor(typeof(AsyncLoggingInterceptor))]
    public MyClass : IMyClass
    {
    }
