### ISSUE TITLE
Can I decorate a class with AsyncInterceptor using dependency injection?

### ISSUE THREAD

**Issue by balintn22** [JSkimming/Castle.Core.AsyncInterceptor#87]
I used to register an interceptor with the DI resolver like this:
    WindsorContainer _container;
    _container.Register(Component.For<ExceptionInterceptor>()
        .ImplementedBy<ExceptionInterceptor>()
        .Named(nameof(ExceptionInterceptor)));

Then decorate a class with the interceptor like this:
    [Interceptor(nameof(ExceptionInterceptor))]
    public class MyClassToBeIntercepted
    {
        // ...
    }

Can I use this method for AsyncInterceptor?

**Comment by JSkimming** [comment]
Can you do this for AsyncInterceptor? Probably.

Does this library provide this support? No.

**Comment by JSkimming** [comment]
Closing as direct DI support is outside the scope of this library.
