### ISSUE TITLE
Question - How can i use IInterceptorSelector with IAsyncInterceptor

### ISSUE THREAD

**Issue by IT-CASADO** [JSkimming/Castle.Core.AsyncInterceptor#89]
Hi,

i need to switch to IAsyncInterceptor and want to use [option 2](https://github.com/JSkimming/Castle.Core.AsyncInterceptor#option-2--implement-iasyncinterceptor-interface-to-intercept-invocations).

If i change my base class to [IAsyncInterceptor](https://github.com/IT-CASADO/Castle-With-Autofac_And_AsyncInterceptors/blob/async/Interceptor.cs#L9), then my [implementation](https://github.com/IT-CASADO/Castle-With-Autofac_And_AsyncInterceptors/blob/async/Interceptor.cs#L84) of AttributeMethodSelector doesn't match the interface definition of IInterceptorSelector anymore.

How can i use IInterceptorSelector in conjunction with IAsyncInterceptor?

**Comment by JSkimming** [comment]
@IT-CASADO I'm not familiar with `IInterceptorSelector` so I can't really give much guidance in that regard. But I can point you to two extensions methods that may help.

`ProxyGeneratorExtensions.ToInterceptor()` and `ProxyGeneratorExtensions.ToInterceptors()` both wrap a `IAsyncInterceptor` instances with a `AsyncDeterminationInterceptor` which itself implements `IInterceptor`.

See the [implementation of those two methods here](https://github.com/JSkimming/Castle.Core.AsyncInterceptor/blob/v2.0.21-alpha/src/Castle.Core.AsyncInterceptor/ProxyGeneratorExtensions.cs#L15-L33 "Implementation of ToInterceptor() and ToInterceptors().").

So, you can use these methods to use an implementation of `IAsyncInterceptor` where you would traditionally use an implementation of `IInterceptor`.

**Comment by IT-CASADO** [comment]
@JSkimming Great, this is working for me now!

I overlooked this in your [documentation](https://github.com/JSkimming/Castle.Core.AsyncInterceptor#using-asyncinterceptor-with-non-overloaded-proxygenerator-methods).
